<?php

/**
 * index.php — front controller + router, all in one.
 *
 * Every request is rewritten here by .htaccess.
 *
 * Route patterns use {param} placeholders, e.g.:
 *
 *     institution/{slug}
 *
 * The matched page file in /pages can read route parameters
 * via $params['slug'].
 */

declare(strict_types=1);

require __DIR__.'/config.php';

// ================================================================
// ROUTES
// ================================================================

$routes = [

    // Home
    '' => 'home.php',

    // Institutions
    'institutions' => 'institutions.php',
    'institutions/{slug}' => 'institution.php',

    // Blog
    'blog' => 'blog.php',
    'blog/{slug}' => 'blog-post.php',

    // Publications
    'publications' => 'publications.php',

    // Reports
    'reports/research-output' => 'research-output.php',
    'reports/citations' => 'citations.php',
    'reports/collaboration' => 'collaboration.php',
    'reports/gender' => 'gender.php',
    'reports/open-access' => 'open-access.php',
    'reports/social-media' => 'social-media.php',
    'reports/grants' => 'grants.php',
    'reports/sdg-research' => 'sdg-research.php',
    'reports/major-institutions' => 'major_inst.php',

    // Others
    'reports/innovation' => 'india_innovation_story.php',

    // Static pages
    'about' => 'about.php',
    'team' => 'team.php',
    'methodology' => 'methodology.php',
    'terms' => 'terms.php',
];

// ================================================================
// GET REQUEST PATH
// ================================================================

$path = trim(
    (string) parse_url(
        $_SERVER['REQUEST_URI'] ?? '/',
        PHP_URL_PATH,
    ),
    '/',
);

// ================================================================
// MATCH ROUTE
// ================================================================

$page = null;
$params = [];

foreach ($routes as $pattern => $file) {

    /*
     * Convert:
     *
     *     institution/{slug}
     *
     * into:
     *
     *     institution/(?P<slug>[A-Za-z0-9\-]+)
     */

    $regexPattern = preg_replace(
        '/\{(\w+)\}/',
        '(?P<$1>[A-Za-z0-9\-]+)',
        $pattern,
    );

    $regex = '#^'.$regexPattern.'$#';

    if (preg_match($regex, $path, $matches)) {

        $page = $file;

        /*
         * Keep only named route parameters.
         *
         * Numeric indexes generated by preg_match()
         * are removed.
         */
        $params = array_filter(
            $matches,
            'is_string',
            ARRAY_FILTER_USE_KEY,
        );

        break;
    }
}

// ================================================================
// 404
// ================================================================

if (
    $page === null ||
    ! file_exists(ROOT_PATH.'/pages/'.$page)
) {
    abort_404();
}

// ================================================================
// RENDER PAGE
// ================================================================
//
// Page templates are loaded first so they can define:
//
//     $pageTitle
//     $pageDescription
//
// before header.php is rendered.
//
// The page's HTML is buffered into $content.
//

$pageFile = ROOT_PATH.'/pages/'.$page;

ob_start();

require $pageFile;

$content = ob_get_clean();

// ================================================================
// LAYOUT
// ================================================================

require ROOT_PATH.'/partials/header.php';

echo $content;

require ROOT_PATH.'/partials/footer.php';
