<?php

declare(strict_types=1);

require __DIR__ . '/../config.php';

header('Content-Type: application/json; charset=utf-8');

$data = [
    [
        'institution' => 'Anna University, Chennai',
        'tp' => 29698,
        'cagr_tp' => 12.64,
        'tc' => 316029,
        'cited_output' => 81.34,
        'h_index' => 134,
        'share_india' => 2.74,
    ],
    [
        'institution' => 'All India Institute of Medical Sciences, Delhi',
        'tp' => 20545,
        'cagr_tp' => 11.02,
        'tc' => 225624,
        'cited_output' => 73.50,
        'h_index' => 127,
        'share_india' => 1.89,
    ],
    [
        'institution' => 'Indian Institute of Science Bangalore',
        'tp' => 20257,
        'cagr_tp' => 4.16,
        'tc' => 308491,
        'cited_output' => 88.40,
        'h_index' => 145,
        'share_india' => 1.87,
    ],
    [
        'institution' => 'Indian Institute of Technology Kharagpur',
        'tp' => 18329,
        'cagr_tp' => 6.46,
        'tc' => 274172,
        'cited_output' => 89.40,
        'h_index' => 127,
        'share_india' => 1.69,
    ],
    [
        'institution' => 'Indian Institute of Technology Bombay',
        'tp' => 17384,
        'cagr_tp' => 7.47,
        'tc' => 235472,
        'cited_output' => 85.00,
        'h_index' => 137,
        'share_india' => 1.60,
    ],
    [
        'institution' => 'Indian Institute of Technology Madras',
        'tp' => 16650,
        'cagr_tp' => 7.33,
        'tc' => 207338,
        'cited_output' => 84.85,
        'h_index' => 126,
        'share_india' => 1.54,
    ],
    [
        'institution' => 'Indian Institute of Technology Delhi',
        'tp' => 15402,
        'cagr_tp' => 8.55,
        'tc' => 232485,
        'cited_output' => 88.38,
        'h_index' => 131,
        'share_india' => 1.42,
    ],
    [
        'institution' => 'University of Delhi',
        'tp' => 15134,
        'cagr_tp' => 5.80,
        'tc' => 235350,
        'cited_output' => 82.95,
        'h_index' => 144,
        'share_india' => 1.40,
    ],
    [
        'institution' => 'Bhabha Atomic Research Centre, Mumbai',
        'tp' => 13752,
        'cagr_tp' => 2.76,
        'tc' => 207521,
        'cited_output' => 91.04,
        'h_index' => 126,
        'share_india' => 1.27,
    ],
    [
        'institution' => 'Post Graduate Institute of Medical Education and Research, Chandigarh',
        'tp' => 13712,
        'cagr_tp' => 9.60,
        'tc' => 142646,
        'cited_output' => 74.85,
        'h_index' => 108,
        'share_india' => 1.26,
    ],
    [
        'institution' => 'Vellore Institute of Technology University',
        'tp' => 12526,
        'cagr_tp' => 22.16,
        'tc' => 150495,
        'cited_output' => 82.77,
        'h_index' => 112,
        'share_india' => 1.16,
    ],
    [
        'institution' => 'Jadavpur University',
        'tp' => 12502,
        'cagr_tp' => 5.61,
        'tc' => 167053,
        'cited_output' => 87.47,
        'h_index' => 112,
        'share_india' => 1.15,
    ],
    [
        'institution' => 'Indian Institute of Technology Roorkee',
        'tp' => 12470,
        'cagr_tp' => 10.17,
        'tc' => 207482,
        'cited_output' => 89.59,
        'h_index' => 138,
        'share_india' => 1.15,
    ],
    [
        'institution' => 'Indian Institute of Technology Kanpur',
        'tp' => 11583,
        'cagr_tp' => 6.35,
        'tc' => 154648,
        'cited_output' => 86.29,
        'h_index' => 107,
        'share_india' => 1.07,
    ],
    [
        'institution' => 'Indian Institute of Technology Guwahati',
        'tp' => 10364,
        'cagr_tp' => 11.64,
        'tc' => 146145,
        'cited_output' => 88.20,
        'h_index' => 110,
        'share_india' => 0.96,
    ],
    [
        'institution' => 'Banaras Hindu University',
        'tp' => 10214,
        'cagr_tp' => 3.48,
        'tc' => 176674,
        'cited_output' => 88.60,
        'h_index' => 126,
        'share_india' => 0.94,
    ],
    [
        'institution' => 'University of Calcutta',
        'tp' => 9703,
        'cagr_tp' => 7.10,
        'tc' => 113064,
        'cited_output' => 84.73,
        'h_index' => 91,
        'share_india' => 0.89,
    ],
    [
        'institution' => 'University of Pune',
        'tp' => 9510,
        'cagr_tp' => 9.75,
        'tc' => 99732,
        'cited_output' => 80.69,
        'h_index' => 101,
        'share_india' => 0.88,
    ],
    [
        'institution' => 'Visvesvaraya Technological University, Belgaum',
        'tp' => 8959,
        'cagr_tp' => 20.14,
        'tc' => 64177,
        'cited_output' => 74.36,
        'h_index' => 74,
        'share_india' => 0.83,
    ],
    [
        'institution' => 'Panjab University',
        'tp' => 8469,
        'cagr_tp' => 6.60,
        'tc' => 171093,
        'cited_output' => 89.82,
        'h_index' => 134,
        'share_india' => 0.78,
    ],
    [
        'institution' => 'Manipal Academy of Higher Education, Manipal',
        'tp' => 8307,
        'cagr_tp' => 18.21,
        'tc' => 74606,
        'cited_output' => 78.21,
        'h_index' => 79,
        'share_india' => 0.77,
    ],
    [
        'institution' => 'Aligarh Muslim University',
        'tp' => 8025,
        'cagr_tp' => 7.60,
        'tc' => 123656,
        'cited_output' => 85.88,
        'h_index' => 113,
        'share_india' => 0.74,
    ],
    [
        'institution' => 'Maulana Azad National Institute of Technology, Bhopal',
        'tp' => 7866,
        'cagr_tp' => 14.15,
        'tc' => 107564,
        'cited_output' => 84.76,
        'h_index' => 107,
        'share_india' => 0.73,
    ],
    [
        'institution' => 'University of Madras',
        'tp' => 7017,
        'cagr_tp' => 5.63,
        'tc' => 96803,
        'cited_output' => 84.30,
        'h_index' => 100,
        'share_india' => 0.65,
    ],
    [
        'institution' => 'University of Hyderabad',
        'tp' => 6651,
        'cagr_tp' => 3.67,
        'tc' => 91303,
        'cited_output' => 84.38,
        'h_index' => 92,
        'share_india' => 0.61,
    ],
    [
        'institution' => 'Indian Institute of Chemical Technology, Hyderabad',
        'tp' => 6519,
        'cagr_tp' => -4.82,
        'tc' => 103422,
        'cited_output' => 77.97,
        'h_index' => 95,
        'share_india' => 0.60,
    ],
    [
        'institution' => 'Jawaharlal Nehru University',
        'tp' => 6363,
        'cagr_tp' => 10.83,
        'tc' => 91933,
        'cited_output' => 79.24,
        'h_index' => 96,
        'share_india' => 0.59,
    ],
    [
        'institution' => 'Amity University, Noida',
        'tp' => 6325,
        'cagr_tp' => 34.77,
        'tc' => 57284,
        'cited_output' => 79.04,
        'h_index' => 80,
        'share_india' => 0.58,
    ],
    [
        'institution' => 'Indian Institute of Technology (ISM) Dhanbad',
        'tp' => 6322,
        'cagr_tp' => 26.13,
        'tc' => 78416,
        'cited_output' => 86.68,
        'h_index' => 91,
        'share_india' => 0.58,
    ],
    [
        'institution' => 'Bharathiar University, Coimbatore',
        'tp' => 6194,
        'cagr_tp' => 12.60,
        'tc' => 88737,
        'cited_output' => 87.49,
        'h_index' => 98,
        'share_india' => 0.57,
    ],
    [
        'institution' => 'Tata Institute of Fundamental Research, Mumbai',
        'tp' => 6152,
        'cagr_tp' => 2.38,
        'tc' => 143789,
        'cited_output' => 88.69,
        'h_index' => 125,
        'share_india' => 0.57,
    ],
    [
        'institution' => 'University of Kerala',
        'tp' => 5834,
        'cagr_tp' => 10.72,
        'tc' => 54766,
        'cited_output' => 79.67,
        'h_index' => 74,
        'share_india' => 0.54,
    ],
    [
        'institution' => 'Annamalai University',
        'tp' => 5376,
        'cagr_tp' => 1.17,
        'tc' => 80872,
        'cited_output' => 87.28,
        'h_index' => 89,
        'share_india' => 0.50,
    ],
    [
        'institution' => 'Christian Medical College & Hospital, Vellore',
        'tp' => 5334,
        'cagr_tp' => 9.09,
        'tc' => 56797,
        'cited_output' => 77.15,
        'h_index' => 83,
        'share_india' => 0.49,
    ],
    [
        'institution' => 'Pondicherry University',
        'tp' => 5064,
        'cagr_tp' => 12.59,
        'tc' => 60962,
        'cited_output' => 83.41,
        'h_index' => 84,
        'share_india' => 0.47,
    ],
    [
        'institution' => 'King Georges Medical University, Lucknow',
        'tp' => 5050,
        'cagr_tp' => 7.70,
        'tc' => 37116,
        'cited_output' => 71.96,
        'h_index' => 62,
        'share_india' => 0.47,
    ],
    [
        'institution' => 'Thapar University, Patiala',
        'tp' => 4987,
        'cagr_tp' => 18.20,
        'tc' => 74715,
        'cited_output' => 88.89,
        'h_index' => 96,
        'share_india' => 0.46,
    ],
    [
        'institution' => 'Bharathidasan University',
        'tp' => 4954,
        'cagr_tp' => 8.70,
        'tc' => 72566,
        'cited_output' => 88.19,
        'h_index' => 86,
        'share_india' => 0.46,
    ],
    [
        'institution' => 'Jamia Milia Islamia',
        'tp' => 4923,
        'cagr_tp' => 11.42,
        'tc' => 77521,
        'cited_output' => 86.63,
        'h_index' => 95,
        'share_india' => 0.45,
    ],
    [
        'institution' => 'National Institute of Technology Rourkela',
        'tp' => 4897,
        'cagr_tp' => 18.84,
        'tc' => 60716,
        'cited_output' => 87.99,
        'h_index' => 72,
        'share_india' => 0.45,
    ],
    [
        'institution' => 'Birla Institute of Technology and Science, Pilani',
        'tp' => 4774,
        'cagr_tp' => 17.88,
        'tc' => 55937,
        'cited_output' => 85.19,
        'h_index' => 76,
        'share_india' => 0.44,
    ],
    [
        'institution' => 'Indian Statistical Institute, Kolkata',
        'tp' => 4751,
        'cagr_tp' => 6.01,
        'tc' => 52270,
        'cited_output' => 84.49,
        'h_index' => 79,
        'share_india' => 0.44,
    ],
    [
        'institution' => 'Sanjay Gandhi Post Graduate Institute of Medical Sciences, Lucknow',
        'tp' => 4652,
        'cagr_tp' => 4.53,
        'tc' => 70416,
        'cited_output' => 74.33,
        'h_index' => 80,
        'share_india' => 0.43,
    ],
    [
        'institution' => 'National Chemical Laboratory, Pune',
        'tp' => 4598,
        'cagr_tp' => -0.12,
        'tc' => 92440,
        'cited_output' => 88.13,
        'h_index' => 110,
        'share_india' => 0.42,
    ],
    [
        'institution' => 'Indian Association for the Cultivation of Science, Kolkata',
        'tp' => 4477,
        'cagr_tp' => -0.36,
        'tc' => 83081,
        'cited_output' => 90.53,
        'h_index' => 98,
        'share_india' => 0.41,
    ],
    [
        'institution' => 'Indian Institute of Engineering Science and Technology, Shibpur',
        'tp' => 4438,
        'cagr_tp' => 11.16,
        'tc' => 44685,
        'cited_output' => 84.84,
        'h_index' => 68,
        'share_india' => 0.41,
    ],
    [
        'institution' => 'National Institute of Mental Health and Neurosciences, Bengaluru',
        'tp' => 4416,
        'cagr_tp' => 11.13,
        'tc' => 45522,
        'cited_output' => 80.89,
        'h_index' => 69,
        'share_india' => 0.41,
    ],
    [
        'institution' => 'National Institute of Technology Tiruchirappalli',
        'tp' => 4353,
        'cagr_tp' => 14.39,
        'tc' => 59008,
        'cited_output' => 86.22,
        'h_index' => 83,
        'share_india' => 0.40,
    ],
    [
        'institution' => 'West Bengal University of Technology, Kolkata',
        'tp' => 4351,
        'cagr_tp' => 11.77,
        'tc' => 41509,
        'cited_output' => 83.29,
        'h_index' => 68,
        'share_india' => 0.40,
    ],
    [
        'institution' => 'Saha Institute of Nuclear Physics, Kolkata',
        'tp' => 4195,
        'cagr_tp' => 6.76,
        'tc' => 89863,
        'cited_output' => 90.49,
        'h_index' => 114,
        'share_india' => 0.39,
    ],
];

$draw = isset($_POST['draw']) ? (int) $_POST['draw'] : 0;

$search = isset($_POST['search']['value'])
    ? trim((string) $_POST['search']['value'])
    : '';

$filtered = $data;

if ($search !== '') {
    $filtered = array_values(array_filter(
        $data,
        static function (array $row) use ($search): bool {
            return stripos($row['institution'], $search) !== false;
        }
    ));
}

echo json_encode([
    'draw' => $draw,
    'recordsTotal' => count($data),
    'recordsFiltered' => count($filtered),
    'data' => $filtered,
], JSON_UNESCAPED_UNICODE);