<?php

declare(strict_types=1);

require __DIR__ . '/../config.php';

header('Content-Type: application/json; charset=utf-8');

$data = [
    [
        'institution' => 'Anna University, Chennai',
        'tp' => 29698,
        'total_oa' => 14.27,
        'gold' => 71.40,
        'green' => 9.11,
        'bronze' => 12.65,
        'hybrid' => 6.84,
    ],
    [
        'institution' => 'All India Institute of Medical Sciences, Delhi',
        'tp' => 20545,
        'total_oa' => 53.23,
        'gold' => 61.58,
        'green' => 15.31,
        'bronze' => 18.38,
        'hybrid' => 4.74,
    ],
    [
        'institution' => 'Indian Institute of Science Bangalore',
        'tp' => 20257,
        'total_oa' => 32.21,
        'gold' => 28.95,
        'green' => 42.99,
        'bronze' => 19.63,
        'hybrid' => 8.43,
    ],
    [
        'institution' => 'Indian Institute of Technology Kharagpur',
        'tp' => 18329,
        'total_oa' => 14.89,
        'gold' => 38.42,
        'green' => 35.68,
        'bronze' => 18.97,
        'hybrid' => 6.92,
    ],
    [
        'institution' => 'Indian Institute of Technology Bombay',
        'tp' => 17384,
        'total_oa' => 20.65,
        'gold' => 35.08,
        'green' => 37.70,
        'bronze' => 18.03,
        'hybrid' => 9.19,
    ],
    [
        'institution' => 'Indian Institute of Technology Madras',
        'tp' => 16650,
        'total_oa' => 18.54,
        'gold' => 39.13,
        'green' => 32.04,
        'bronze' => 18.14,
        'hybrid' => 10.69,
    ],
    [
        'institution' => 'Indian Institute of Technology Delhi',
        'tp' => 15402,
        'total_oa' => 15.48,
        'gold' => 42.74,
        'green' => 31.59,
        'bronze' => 17.99,
        'hybrid' => 7.68,
    ],
    [
        'institution' => 'University of Delhi',
        'tp' => 15134,
        'total_oa' => 31.65,
        'gold' => 50.44,
        'green' => 19.21,
        'bronze' => 15.85,
        'hybrid' => 14.51,
    ],
    [
        'institution' => 'Bhabha Atomic Research Centre, Mumbai',
        'tp' => 13752,
        'total_oa' => 23.74,
        'gold' => 45.30,
        'green' => 23.09,
        'bronze' => 11.00,
        'hybrid' => 20.61,
    ],
    [
        'institution' => 'Post Graduate Institute of Medical Education and Research, Chandigarh',
        'tp' => 13712,
        'total_oa' => 50.49,
        'gold' => 57.27,
        'green' => 18.16,
        'bronze' => 20.06,
        'hybrid' => 4.51,
    ],
    [
        'institution' => 'Vellore Institute of Technology University',
        'tp' => 12526,
        'total_oa' => 23.11,
        'gold' => 77.58,
        'green' => 8.88,
        'bronze' => 8.39,
        'hybrid' => 5.15,
    ],
    [
        'institution' => 'Jadavpur University',
        'tp' => 12502,
        'total_oa' => 16.69,
        'gold' => 47.94,
        'green' => 30.97,
        'bronze' => 15.00,
        'hybrid' => 6.09,
    ],
    [
        'institution' => 'Indian Institute of Technology Roorkee',
        'tp' => 12470,
        'total_oa' => 14.19,
        'gold' => 50.90,
        'green' => 20.23,
        'bronze' => 20.28,
        'hybrid' => 8.59,
    ],
    [
        'institution' => 'Indian Institute of Technology Kanpur',
        'tp' => 11583,
        'total_oa' => 21.51,
        'gold' => 27.13,
        'green' => 46.83,
        'bronze' => 16.81,
        'hybrid' => 9.23,
    ],
    [
        'institution' => 'Indian Institute of Technology Guwahati',
        'tp' => 10364,
        'total_oa' => 18.63,
        'gold' => 38.43,
        'green' => 26.46,
        'bronze' => 13.05,
        'hybrid' => 22.06,
    ],
    [
        'institution' => 'Banaras Hindu University',
        'tp' => 10214,
        'total_oa' => 25.88,
        'gold' => 47.64,
        'green' => 26.64,
        'bronze' => 16.46,
        'hybrid' => 9.27,
    ],
    [
        'institution' => 'University of Calcutta',
        'tp' => 9703,
        'total_oa' => 22.81,
        'gold' => 44.78,
        'green' => 31.13,
        'bronze' => 16.72,
        'hybrid' => 7.37,
    ],
    [
        'institution' => 'University of Pune',
        'tp' => 9510,
        'total_oa' => 19.67,
        'gold' => 50.94,
        'green' => 22.61,
        'bronze' => 17.26,
        'hybrid' => 9.19,
    ],
    [
        'institution' => 'Visvesvaraya Technological University, Belgaum',
        'tp' => 8959,
        'total_oa' => 16.54,
        'gold' => 70.04,
        'green' => 12.15,
        'bronze' => 9.78,
        'hybrid' => 8.03,
    ],
    [
        'institution' => 'Panjab University',
        'tp' => 8469,
        'total_oa' => 37.93,
        'gold' => 44.65,
        'green' => 16.78,
        'bronze' => 8.78,
        'hybrid' => 29.79,
    ],
    [
        'institution' => 'Manipal Academy of Higher Education, Manipal',
        'tp' => 8307,
        'total_oa' => 43.95,
        'gold' => 59.30,
        'green' => 16.43,
        'bronze' => 17.09,
        'hybrid' => 7.18,
    ],
    [
        'institution' => 'Aligarh Muslim University',
        'tp' => 8025,
        'total_oa' => 30.26,
        'gold' => 66.72,
        'green' => 14.25,
        'bronze' => 11.82,
        'hybrid' => 7.21,
    ],
    [
        'institution' => 'Maulana Azad National Institute of Technology, Bhopal',
        'tp' => 7866,
        'total_oa' => 17.35,
        'gold' => 67.69,
        'green' => 10.26,
        'bronze' => 13.33,
        'hybrid' => 8.72,
    ],
    [
        'institution' => 'University of Madras',
        'tp' => 7017,
        'total_oa' => 30.41,
        'gold' => 73.43,
        'green' => 10.64,
        'bronze' => 9.18,
        'hybrid' => 6.75,
    ],
    [
        'institution' => 'University of Hyderabad',
        'tp' => 6651,
        'total_oa' => 23.21,
        'gold' => 49.87,
        'green' => 21.76,
        'bronze' => 21.50,
        'hybrid' => 6.87,
    ],
    [
        'institution' => 'Indian Institute of Chemical Technology, Hyderabad',
        'tp' => 6519,
        'total_oa' => 10.69,
        'gold' => 50.50,
        'green' => 19.23,
        'bronze' => 22.53,
        'hybrid' => 7.75,
    ],
    [
        'institution' => 'Jawaharlal Nehru University',
        'tp' => 6363,
        'total_oa' => 30.32,
        'gold' => 52.15,
        'green' => 21.00,
        'bronze' => 19.34,
        'hybrid' => 7.52,
    ],
    [
        'institution' => 'Amity University, Noida',
        'tp' => 6325,
        'total_oa' => 18.17,
        'gold' => 57.62,
        'green' => 18.54,
        'bronze' => 14.27,
        'hybrid' => 9.57,
    ],
    [
        'institution' => 'Indian Institute of Technology (ISM) Dhanbad',
        'tp' => 6322,
        'total_oa' => 12.51,
        'gold' => 63.46,
        'green' => 8.22,
        'bronze' => 21.74,
        'hybrid' => 6.57,
    ],
    [
        'institution' => 'Bharathiar University, Coimbatore',
        'tp' => 6194,
        'total_oa' => 24.09,
        'gold' => 67.56,
        'green' => 13.00,
        'bronze' => 11.19,
        'hybrid' => 8.24,
    ],
    [
        'institution' => 'Tata Institute of Fundamental Research, Mumbai',
        'tp' => 6152,
        'total_oa' => 69.98,
        'gold' => 26.04,
        'green' => 37.98,
        'bronze' => 12.36,
        'hybrid' => 23.62,
    ],
    [
        'institution' => 'University of Kerala',
        'tp' => 5834,
        'total_oa' => 31.49,
        'gold' => 62.22,
        'green' => 17.42,
        'bronze' => 11.92,
        'hybrid' => 8.44,
    ],
    [
        'institution' => 'Annamalai University',
        'tp' => 5376,
        'total_oa' => 28.92,
        'gold' => 61.35,
        'green' => 11.06,
        'bronze' => 9.65,
        'hybrid' => 17.94,
    ],
    [
        'institution' => 'Christian Medical College & Hospital, Vellore',
        'tp' => 5334,
        'total_oa' => 58.98,
        'gold' => 59.09,
        'green' => 16.34,
        'bronze' => 16.69,
        'hybrid' => 7.88,
    ],
    [
        'institution' => 'Pondicherry University',
        'tp' => 5064,
        'total_oa' => 21.45,
        'gold' => 60.22,
        'green' => 17.77,
        'bronze' => 14.00,
        'hybrid' => 8.01,
    ],
    [
        'institution' => 'King Georges Medical University, Lucknow',
        'tp' => 5050,
        'total_oa' => 60.97,
        'gold' => 50.11,
        'green' => 30.95,
        'bronze' => 15.26,
        'hybrid' => 3.67,
    ],
    [
        'institution' => 'Thapar University, Patiala',
        'tp' => 4987,
        'total_oa' => 11.79,
        'gold' => 54.08,
        'green' => 20.58,
        'bronze' => 19.56,
        'hybrid' => 5.78,
    ],
    [
        'institution' => 'Bharathidasan University',
        'tp' => 4954,
        'total_oa' => 26.67,
        'gold' => 56.32,
        'green' => 23.47,
        'bronze' => 10.14,
        'hybrid' => 10.07,
    ],
    [
        'institution' => 'Jamia Milia Islamia',
        'tp' => 4923,
        'total_oa' => 28.62,
        'gold' => 57.35,
        'green' => 25.34,
        'bronze' => 10.01,
        'hybrid' => 7.31,
    ],
    [
        'institution' => 'National Institute of Technology Rourkela',
        'tp' => 4897,
        'total_oa' => 13.62,
        'gold' => 57.72,
        'green' => 15.44,
        'bronze' => 20.69,
        'hybrid' => 6.15,
    ],
    [
        'institution' => 'Birla Institute of Technology and Science, Pilani',
        'tp' => 4774,
        'total_oa' => 21.87,
        'gold' => 53.83,
        'green' => 27.97,
        'bronze' => 11.02,
        'hybrid' => 7.18,
    ],
    [
        'institution' => 'Indian Statistical Institute, Kolkata',
        'tp' => 4751,
        'total_oa' => 35.02,
        'gold' => 22.00,
        'green' => 56.67,
        'bronze' => 16.47,
        'hybrid' => 4.87,
    ],
    [
        'institution' => 'Sanjay Gandhi Post Graduate Institute of Medical Sciences, Lucknow',
        'tp' => 4652,
        'total_oa' => 51.48,
        'gold' => 61.75,
        'green' => 17.04,
        'bronze' => 17.04,
        'hybrid' => 4.18,
    ],
    [
        'institution' => 'National Chemical Laboratory, Pune',
        'tp' => 4598,
        'total_oa' => 15.68,
        'gold' => 45.08,
        'green' => 21.50,
        'bronze' => 21.64,
        'hybrid' => 11.79,
    ],
    [
        'institution' => 'Indian Association for the Cultivation of Science, Kolkata',
        'tp' => 4477,
        'total_oa' => 20.55,
        'gold' => 27.61,
        'green' => 50.33,
        'bronze' => 11.20,
        'hybrid' => 10.87,
    ],
    [
        'institution' => 'Indian Institute of Engineering Science and Technology, Shibpur',
        'tp' => 4438,
        'total_oa' => 13.29,
        'gold' => 53.05,
        'green' => 29.15,
        'bronze' => 10.00,
        'hybrid' => 7.80,
    ],
    [
        'institution' => 'National Institute of Mental Health and Neurosciences, Bengaluru',
        'tp' => 4416,
        'total_oa' => 44.25,
        'gold' => 68.53,
        'green' => 11.98,
        'bronze' => 13.25,
        'hybrid' => 6.24,
    ],
    [
        'institution' => 'National Institute of Technology Tiruchirappalli',
        'tp' => 4353,
        'total_oa' => 10.34,
        'gold' => 62.22,
        'green' => 16.89,
        'bronze' => 12.89,
        'hybrid' => 8.00,
    ],
    [
        'institution' => 'West Bengal University of Technology, Kolkata',
        'tp' => 4351,
        'total_oa' => 17.33,
        'gold' => 53.45,
        'green' => 30.64,
        'bronze' => 10.08,
        'hybrid' => 5.84,
    ],
];

$draw = isset($_POST['draw']) ? (int) $_POST['draw'] : 0;

$search = isset($_POST['search']['value'])
    ? trim((string) $_POST['search']['value'])
    : '';

$filtered = $data;

if ($search !== '') {
    $filtered = array_values(array_filter(
        $data,
        static function (array $row) use ($search): bool {
            return stripos($row['institution'], $search) !== false;
        }
    ));
}

echo json_encode([
    'draw' => $draw,
    'recordsTotal' => count($data),
    'recordsFiltered' => count($filtered),
    'data' => $filtered,
], JSON_UNESCAPED_UNICODE);